using System;

namespace MiswGame2007
{
    public enum GameImage
    {
        TestImage = 0,
        Block,
        Player,
        PlayerBullet,
        PlayerBulletExplosion,
        Background1,
        Background2,
        Background3,
        Background4,
        Background5,
        Item,
        Hud,
        BigExplosion,
        House,
        Baaka,
        EnemyBullet,
        Babo,
        Kyoro,
        Nurunuru,
        Byaa,
        Debris,
        ItemExplosion,
        Aurora,
        Norio,
        HouseBoss,
        Title,
        ItemEnemy,
        BigHanabi,
        SmallHanabi,
        MushroomBoss1,
        MushroomBoss2,
        MushroomBoss3,
        Mushroom,
        EggMachine,
        Oyaji,
        Robot,
        OyajiThunder,
        Message,
        Number,
        Father,
        Staff,
        Skater,
        Rain,
        BlackPlayer,
        Worm,
        Starman,
        Penguin,
        Mafia
    }
}
